### ISSUE TITLE
Suggest adding a NEWS.md

### ISSUE THREAD

**Issue by mikelove** [keyes-timothy/tidytof#5]
We were asked by reviewers to provide changelogs for each package. Pkgdown will render these nicely if you add a `NEWS.md` file. You don't have to back-date, you can just start now and keep track of changes going forward.

https://nullranges.github.io/nullranges/news/index.html

https://github.com/nullranges/nullranges/blob/HEAD/NEWS.md

**Comment by keyes-timothy** [comment]
Added! Thanks for the note.
