### ISSUE TITLE
Repo refactoring for tidyomics

### ISSUE THREAD

**Issue by stemangiola** [keyes-timothy/tidytof#6]
I write here because my email bounced back from your Stanford address.

---------------

Hello Timothy,
 
I hope you are well.
 
I was wondering, all in line for the submission to this Bioc release? Bioconductor mentioned that late submissions this year will likely not be considered.
 
Do you want us to review the refactored repos?

----------------

**Comment by keyes-timothy** [comment]
Hi Stefano! 

I've abstracted the flowCore integration into its own package. The GitHub repo is [here](https://github.com/keyes-timothy/tidyFlowCore/) and the website is [here](https://keyes-timothy.github.io/tidyFlowCore/). 

I'll be submitting to Bioconductor soon! Feel free to take a peek and make any suggestions (e.g. better referencing to tidyomics, features that should be included to match other tidyomics packages better, etc.)

**Comment by stemangiola** [comment]
Congrats! I will have a look into more details soon.
